### ISSUE TITLE
Incompatible with ui3d2d 

### ISSUE THREAD

**Issue by Riddle1001** [Jaffies/paint#4]
I've been using https://github.com/TomDotBat/ui3d2d for a lot of my 3d2d UIs, sadly though I cannot use paint lib with it as nothing seems to be drawn on the 3d2d. Hopefully there is a solution that can solve this problem. Thanks!

**Comment by Jaffies** [comment]
https://media.discordapp.net/attachments/1262259031335243877/1266217802470264913/4c29892411c2670f.png?ex=66a458b9&is=66a30739&hm=7e5383abd412eb8f55aa06ce65d5bfd0dc2dc03170df2a7984b3b150f69f8ca0&=&format=webp&quality=lossless&width=751&height=444
https://media.discordapp.net/attachments/1262259031335243877/1266218087485542412/4b2c7f9fa016d2db.png?ex=66a458fd&is=66a3077d&hm=73de4f5b966834bff96f66c9b0261c575d7f32cabdab9374197a46966ecefd1f&=&format=webp&quality=lossless&width=643&height=444
I can't reproduce your bug. Can you give me the code?

**Comment by Riddle1001** [comment]
> https://media.discordapp.net/attachments/1262259031335243877/1266217802470264913/4c29892411c2670f.png?ex=66a458b9&is=66a30739&hm=7e5383abd412eb8f55aa06ce65d5bfd0dc2dc03170df2a7984b3b150f69f8ca0&=&format=webp&quality=lossless&width=751&height=444 https://media.discordapp.net/attachments/1262259031335243877/1266218087485542412/4b2c7f9fa016d2db.png?ex=66a458fd&is=66a3077d&hm=73de4f5b966834bff96f66c9b0261c575d7f32cabdab9374197a46966ecefd1f&=&format=webp&quality=lossless&width=643&height=444 I can't reproduce your bug. Can you give me the code?

The code is a bit complex as it's attaching it to an entity. I also am using the `ui3d2d.drawVgui` function which I should've mentioned. Are you using `ui3d2d.drawVgui` as well? If not I can whip up an example tomorrow

**Comment by Jaffies** [comment]
> > https://media.discordapp.net/attachments/1262259031335243877/1266217802470264913/4c29892411c2670f.png?ex=66a458b9&is=66a30739&hm=7e5383abd412eb8f55aa06ce65d5bfd0dc2dc03170df2a7984b3b150f69f8ca0&=&format=webp&quality=lossless&width=751&height=444 https://media.discordapp.net/attachments/1262259031335243877/1266218087485542412/4b2c7f9fa016d2db.png?ex=66a458fd&is=66a3077d&hm=73de4f5b966834bff96f66c9b0261c575d7f32cabdab9374197a46966ecefd1f&=&format=webp&quality=lossless&width=643&height=444 I can't reproduce your bug. Can you give me the code?
> 
> The code is a bit complex as it's attaching it to an entity. I also am using the `ui3d2d.drawVgui` function which I should've mentioned. Are you using `ui3d2d.drawVgui` as well? If not I can whip up an example tomorrow. I am using the paint lib inside the panel's paint, the gist of the code is
> 
> ```lua
> local PrinterOverviewScreen = {
>        
>     Paint = function(self, w, h)
>         surface.SetDrawColor( 50, 50, 50, 200 )
> 		surface.DrawRect(0, 0, w, h )
> 		paint.startPanel( self )
>             paint.rects.drawRect(0, 0, w, h, {Color(255, 0, 0), Color(255, 0, 0), Color(0, 0, 255), color_white})
> 		paint.endPanel()
> 
>     end,
> end
> ```
> 
> ```lua
>     cam.Start3D()
>         ui3d2d.drawVgui(overview_screen, centeredPanelPos ,ang , 0.2, LocalPlayer())
>     cam.End3D()
> ```
I got what happened with you. The problem is that paint.startPanel actually starts a new matrix projection, instead of multiplying an existed one. I will add a third argument to paint.startPanel to make a new projection be multiplyed.
You should make use something like ```lua
paint.startPanel(self, true, false, true)``` after an update to make 3d2dui work as well.
